#!/usr/bin/env python
#
# Copyright 2007 Diane Trout
# This software is covered by the GNU Lesser Public License 2.1
#

import sys
from benderjab.xsend import main

if __name__ == "__main__":
  sys.exit(main(sys.argv))
